/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...404]': RouteRecordInfo<
      '/[...404]',
      '/:404(.*)',
      { 404: ParamValue<true> },
      { 404: ParamValue<false> },
      | never
    >,
    '/admin': RouteRecordInfo<
      '/admin',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/new': RouteRecordInfo<
      '/new',
      '/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/post/[user]/[slug]': RouteRecordInfo<
      '/post/[user]/[slug]',
      '/post/:user/:slug',
      { user: ParamValue<true>, slug: ParamValue<true> },
      { user: ParamValue<false>, slug: ParamValue<false> },
      | '/post/[user]/[slug]/edit'
    >,
    '/post/[user]/[slug]/edit': RouteRecordInfo<
      '/post/[user]/[slug]/edit',
      '/post/:user/:slug/edit',
      { user: ParamValue<true>, slug: ParamValue<true> },
      { user: ParamValue<false>, slug: ParamValue<false> },
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | '/settings/'
      | '/settings/account'
      | '/settings/password'
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/account': RouteRecordInfo<
      '/settings/account',
      '/settings/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/password': RouteRecordInfo<
      '/settings/password',
      '/settings/password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/[user]': RouteRecordInfo<
      '/user/[user]',
      '/user/:user',
      { user: ParamValue<true> },
      { user: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...404].vue': {
      routes:
        | '/[...404]'
      views:
        | never
      pathParamNames:
        | '404'
    }
    'src/pages/admin.vue': {
      routes:
        | '/admin'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/new.vue': {
      routes:
        | '/new'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/post/[user]/[slug].vue': {
      routes:
        | '/post/[user]/[slug]'
        | '/post/[user]/[slug]/edit'
      views:
        | 'default'
      pathParamNames:
        | 'slug'
    }
    'src/pages/post/[user]/[slug]/edit.vue': {
      routes:
        | '/post/[user]/[slug]/edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
        | '/settings/'
        | '/settings/account'
        | '/settings/password'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/account.vue': {
      routes:
        | '/settings/account'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/password.vue': {
      routes:
        | '/settings/password'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/user/[user].vue': {
      routes:
        | '/user/[user]'
      views:
        | never
      pathParamNames:
        | 'user'
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
